In [1]:
import numpy as np 

In [4]:
arr=np.arange(5)

In [5]:
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save('myarray',arr)

In [7]:
arr=np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr

In [9]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [10]:
arr1=np.load('myarray.npy')

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [13]:
arr2 = arr 

SyntaxError: invalid character in identifier (<ipython-input-13-37ddf293ffe8>, line 1)

In [14]:
arr2=arr

In [15]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [17]:
archive_array=np.load('ziparray.npz')

In [18]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [20]:
arr= np.array([[1,2,3],[4,5,6]])

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.savetxt('myarraytext.txt',arr,delimiter=',')

In [23]:
arr=np.loadtxt('myarraytext.txt',delimiter=',')

In [24]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])