In [1]:
import numpy as np 
import pandas as pd 
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 =Series([3,4],index=['X','Y'])

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 =DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [13]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.639162  1.500254  1.488304       NaN
1  0.912099 -0.030686  0.077996       NaN
2 -1.381555 -0.281579  0.223408       NaN
3 -0.908196  0.362049 -1.699448       NaN
0  0.328841 -0.248557       NaN -0.268254
1  0.233092 -0.800451       NaN  0.960949
2  1.358331 -0.033375       NaN -2.820171

In [14]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -0.639162  1.500254  1.488304       NaN
1  0.912099 -0.030686  0.077996       NaN
2 -1.381555 -0.281579  0.223408       NaN
3 -0.908196  0.362049 -1.699448       NaN
4  0.328841 -0.248557       NaN -0.268254
5  0.233092 -0.800451       NaN  0.960949
6  1.358331 -0.033375       NaN -2.820171