In [2]:
import numpy as np 

In [5]:
my_list=[1,2,3,4]

In [6]:
my_array1=np.array(my_list)

In [9]:
my_array1

array([1, 2, 3, 4])

In [10]:
my_list2=[11,22,33,44]

In [11]:
my_lists=[my_list,my_list2]

In [12]:
my_array2=np.array(my_lists)

In [13]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [15]:
my_array2.shape

(2, 4)

In [17]:
my_array2.dtype

dtype('int64')

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
my_zeros_array=np.zeros(5)

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
5

TypeError: empty() missing required argument 'shape' (pos 1)

In [23]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])