In [1]:
import numpy as np 

In [2]:
arr =np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
 A=np.random.randn(10)

In [5]:
A

array([ 1.291028  , -0.36838758,  0.30418271,  1.53943958, -1.01003444,
       -1.21628238, -0.90023069, -0.62347634, -0.17129497, -1.51553987])

In [6]:
B=np.random.randn(10)
B

array([ 0.44766536,  0.3884184 , -1.26041469, -0.18111309, -0.66436643,
        0.21082852, -1.0588152 ,  0.04346639, -0.76975074,  0.0972795 ])

In [7]:
#BInary functions 
np.add(A,B)

array([ 1.73869336,  0.02003083, -0.95623198,  1.35832649, -1.67440087,
       -1.00545386, -1.95904589, -0.58000995, -0.94104572, -1.41826037])

In [8]:
np.maximum(A,B)

array([ 1.291028  ,  0.3884184 ,  0.30418271,  1.53943958, -0.66436643,
        0.21082852, -0.90023069,  0.04346639, -0.17129497,  0.0972795 ])